spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/comppress?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.mailbox.org
    username: no-reply@comppress.org
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
server:
  port: 8080
  servlet:
    context-path: /custom-news-api
scheduler:
  triggeringIntervalMilliSeconds: 20000
  initialDelayIntervalMilliSeconds: 5000
  enabled: no
jwt:
  secret: secret