spring:
  task:
    scheduling:
      pool:
        size: 2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/comppress?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.mailbox.org
    username: no-reply@comppress.org
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
server:
  port: 8080
  servlet:
    context-path: /custom-news-api
scheduler:
  news-feed:
    triggeringIntervalMilliSeconds: 40000
    initialDelayIntervalMilliSeconds: 5000
    enabled: yes
  paywall:
    triggeringIntervalMilliSeconds: 20000
    initialDelayIntervalMilliSeconds: 4000
    enabled: yes
    page-size: 100
jwt:
  secret: secret
executor:
  core:
    pool:
      size: 100
  max:
    pool:
      size: 1000
  queue:
    size: 100
#logging:
#  file:
#    name: /var/log/comppress.log
#  logback:
#    rollingpolicy:
#      max-file-size: 25MB
#      max-history: 7