apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "news-api.fullname" . }}
  labels:
    {{- include "news-api.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "news-api.fullname" . }}
            port:
              number: {{ .Values.service.port }}