ALTER TABLE article AUTO_INCREMENT = 1;
ALTER TABLE category AUTO_INCREMENT = 1;
ALTER TABLE criteria AUTO_INCREMENT = 1;
ALTER TABLE publisher AUTO_INCREMENT = 1;
ALTER TABLE rating AUTO_INCREMENT = 1;
ALTER TABLE rss_feed AUTO_INCREMENT = 1;
ALTER TABLE twitter_tweet AUTO_INCREMENT = 1;
ALTER TABLE user AUTO_INCREMENT = 1;

