replicaCount: 1

image:
  repository: ghcr.io/lukonjun/custom-news-api
  pullPolicy: IfNotPresent

env:          
  SPRING_DATASOURCE_PASSWORD: "1234"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/comppress?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
  SPRING_MAIL_PASSWORD: "1234"
  SERVER_PORT: 8080
  TWITTER_API_KEY: "1234"
  TWITTER_API_SECRET: "1234"
  TWITTER_ACCESS_TOKEN: "1234"
  TWITTER_ACCESS_TOKEN_SECRET: "1234"
  scheduler.news-feed.enabled: "yes"
  scheduler.paywall.enabled: "yes"
  scheduler.twitter.enabled: "yes"

nameOverride: "api-production"

service:
  type: ClusterIP
  port: 80

ingress:
  host: api.comppress.org
  issuer: letsencrypt-prod
  class: nginx

resources:
  requests:
    cpu: 200m
    memory: 256Mi
