replicaCount: 1

image:
  repository: ghcr.io/lukonjun/custom-news-api
  pullPolicy: IfNotPresent

env:          
  SPRING_DATASOURCE_PASSWORD: "1234"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/comppress?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
  SPRING_MAIL_PASSWORD: "1234"
  SERVER_PORT: 8080
  TWITTER_API_KEY: "1234"
  TWITTER_API_SECRET: "1234"
  TWITTER_ACCESS_TOKEN: "1234"
  TWITTER_ACCESS_TOKEN_SECRET: "1234"
  scheduler.news-feed.enabled: "yes"
  scheduler.paywall.enabled: "yes"
  scheduler.twitter.enabled: "yes"

nameOverride: "api-staging"

ingress:
  host: api.staging.comppress.org
  issuer: letsencrypt-prod
  class: nginx

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi