name: Application Pipeline
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - src/**
    - docker-compose.yml.j2
    - Dockerfile
  pull_request:
    branches: [main]
    paths:
    - hello-world/**
    - docker-compose.yml.j2
    - Dockerfile

jobs:
  compile-test-build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Build jar with Maven
      run: mvn clean install -Dmaven.test.skip=true
    - name: Build Container Image
      run: docker build --tag ghcr.io/lukonjun/custom-news-api:${{ github.run_id }} .
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Run docker push
      run: docker push ghcr.io/lukonjun/custom-news-api:${{ github.run_id }}
      
  deploy-to-infrastructure:
    runs-on: ubuntu-latest
    needs:
      - compile-test-build-push
    steps:
    - uses: actions/checkout@v2
    - name: create file with ssh key
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/id_rsa
        echo '${{ secrets.STAGE_PRIVATE_KEY }}' >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: run ansible script 
      run: ansible-playbook -i host.ini deploy.yml --extra-vars "token=${{ secrets.GITHUB_TOKEN }} image_name=ghcr.io/lukonjun/custom-news-api:${{ github.run_id }}"
      working-directory: ./ansible
