name: Pipeline Production
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-push-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Build jar with Maven
        run: mvn clean install -Dmaven.test.skip=true
      - name: Build Container Image
        run: docker build --tag ghcr.io/lukonjun/custom-news-api:${{ github.run_id }} .
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Run docker push
        run: docker push ghcr.io/lukonjun/custom-news-api:${{ github.run_id }}
      - name: kubectl set up
        run: |
          mkdir ~/.kube/
          touch ~/.kube/config
          echo '${{ secrets.KUBECONFIG }}' > ~/.kube/config
      - name: test
        run: kubectl get nodes
      - name: helm deploy
        run: >
          helm upgrade
          --install api-production ./news-api
          --namespace production --create-namespace
          --values production.yml
          --set image.tag="${{ github.run_id }}" 
          --set env.SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}"
          --set env.SPRING_DATASOURCE_USERNAME=lucas 
          --set env.SPRING_DATASOURCE_URL="${{ secrets.PRD_DB_CONNECTION_STRING }}"
          --set env.SPRING_MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
          --set env.TWITTER_ACCESS_TOKEN="${{ secrets.PRODUCTION_TWITTER_ACCESS_TOKEN }}"
          --set env.TWITTER_ACCESS_TOKEN_SECRET:="${{ secrets.PRODUCTION_TWITTER_ACCESS_TOKEN_SECRET }}"
          --set env.TWITTER_API_KEY="${{ secrets.PRODUCTION_TWITTER_API_KEY }}"
          --set env.TWITTER_API_SECRET="${{ secrets.PRODUCTION_TWITTER_API_SECRET }}"

        working-directory: ./helm
